# -*- coding: utf-8 -*-
"""em_algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JMF29-EK3mjiPnyEQgd8-EC-V1EZjUtG
"""

from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
import sklearn.metrics as metrics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width',
'Class']
dataset = pd.read_csv("/content/8-dataset.csv", names=names)
X = dataset.iloc[:, :-1]
label = {'Iris-setosa': 0,'Iris-versicolor': 1, 'Iris-virginica': 2}
y = [label[c] for c in dataset.iloc[:, -1]]

#Kmeans Algorithm
model=KMeans(n_clusters=3, random_state=0).fit(X)
print('The accuracy score of K-Mean: ',metrics.accuracy_score(y,
model.labels_))
print('The Confusion matrix of K-Mean:\n',metrics.confusion_matrix(y,
model.labels_))

#EM Algorithm
gmm=GaussianMixture(n_components=3, random_state=0).fit(X)
y_cluster_gmm=gmm.predict(X)
print('The accuracy score of EM: ',metrics.accuracy_score(y,
y_cluster_gmm))

print('The Confusion matrix of EM:\n ',metrics.confusion_matrix(y,
y_cluster_gmm))